apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-api-external-secret
spec:
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: TODO_PROD_RDS_SECRET_ARN
        property: password
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: TODO_PROD_BACKEND_API_SECRET_ARN
        property: JWT_SECRET_KEY
    - secretKey: INTERNAL_CALLBACK_TOKEN
      remoteRef:
        key: TODO_PROD_BACKEND_API_SECRET_ARN
        property: INTERNAL_CALLBACK_TOKEN
    - secretKey: INTERNAL_CALLBACK_HMAC_SECRET
      remoteRef:
        key: TODO_PROD_BACKEND_API_SECRET_ARN
        property: INTERNAL_CALLBACK_HMAC_SECRET
    - secretKey: REDIS_AUTH_TOKEN
      remoteRef:
        key: TODO_PROD_REDIS_AUTH_TOKEN_SECRET_ARN
        property: REDIS_AUTH_TOKEN
