apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-api-config
data:
  APP_ENV: "prod"
  APP_NAME: "utterai-backend"
  API_PREFIX: "/api/v1"
  LOG_LEVEL: "INFO"
  FRONTEND_ORIGIN: "https://utterai.com"
  CORS_ALLOW_ORIGINS: "https://utterai.com"
  CORS_ORIGINS: '["https://utterai.com"]'
  DB_HOST: "utterai-prod-rds.c76womumyurf.ap-northeast-2.rds.amazonaws.com"
  DB_USER: "utterai_app"
  DB_PORT: "5432"
  DB_NAME: "utterai"
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "20"
  REDIS_HOST: "master.utterai-prod-redis.kk4y3f.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_TLS_ENABLED: "true"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  REFRESH_TOKEN_EXPIRE_DAYS: "14"
  AWS_REGION: "ap-northeast-2"
  RAW_AUDIO_BUCKET: "utterai-prod-raw-audio"
  TEMPLATE_BUCKET: "utterai-prod-template"
  S3_RAW_AUDIO_BUCKET: "utterai-prod-raw-audio"
  S3_DOCUMENT_BUCKET: "utterai-prod-rag-ingest"
  S3_REPORT_BUCKET: "utterai-prod-reports"
  PRESIGNED_URL_EXPIRE_SECONDS: "900"
  SQS_AUDIO_PREPROCESS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-prod-audio-preprocess-queue"
  SQS_REPORT_ANALYSIS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-prod-report-analysis-queue"
  OTEL_SERVICE_NAME: "backend"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.utterai-observability.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod,team=utterai,service=backend"
  CLOUDWATCH_LOG_GROUP: "/aws/eks/utterai-prod/backend"
