apiVersion: v1
kind: Service
metadata:
  name: utterai-ai-api-service
  labels:
    app.kubernetes.io/name: utterai-ai-api
    app.kubernetes.io/part-of: utterai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: utterai-ai-api
  ports:
    - name: http
      port: 8080
      targetPort: http
