apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-ai-api-sa
  namespace: utterai-ai-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::032886669461:role/utterai-dev-ai-api-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-cpu-worker-sa
  namespace: utterai-ai-cpu
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::032886669461:role/utterai-dev-ai-cpu-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-ml-gpu-worker-sa
  namespace: utterai-ai-gpu
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::032886669461:role/utterai-dev-ai-ml-gpu-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-batch-worker-sa
  namespace: utterai-batch
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::032886669461:role/utterai-dev-batch-irsa-role
