---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utterai-api
resources:
- namespace.yaml
- "../../base"
- deployment.yaml
- hpa.yaml
images:
- name: utterai-backend
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-backend'
  newTag: dev-dc7bf48
