---
apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-api-config
data:
  APP_ENV: dev
  LOG_LEVEL: DEBUG
  FRONTEND_ORIGIN: https://d129p1nkqgquw3.cloudfront.net
  CORS_ALLOW_ORIGINS: https://d129p1nkqgquw3.cloudfront.net
  DB_HOST: utterai-dev-tokyo-rds.cjuwgumomrw9.ap-northeast-1.rds.amazonaws.com
  REDIS_HOST: master.utterai-dev-tokyo-redis.fju80c.apne1.cache.amazonaws.com
  S3_BUCKET_AUDIO: utterai-dev-tokyo-raw-audio
  S3_BUCKET_TEMPLATE: utterai-dev-tokyo-documents
  S3_BUCKET_TRANSCRIPT: utterai-dev-tokyo-transcripts
  AWS_REGION: ap-northeast-1
  SQS_AUDIO_PREPROCESS_QUEUE_URL: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-audio-preprocess-queue
  SQS_REPORT_ANALYSIS_QUEUE_URL: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-report-analysis-queue
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev-tokyo,team=utterai
  CLOUDWATCH_LOG_GROUP: "/aws/eks/utterai-dev-tokyo/backend"
  CORS_ORIGINS: '["https://d129p1nkqgquw3.cloudfront.net","http://localhost:5173"]'
