---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-api-external-secret
spec:
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "rds!db-d12760bc-f820-4192-943a-0d303bda35e2-zmmQhw"
      property: password
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: utterai-dev-tokyo/backend-api-secret
      property: JWT_SECRET_KEY
  - secretKey: INTERNAL_CALLBACK_TOKEN
    remoteRef:
      key: utterai-dev-tokyo/backend-api-secret
      property: INTERNAL_CALLBACK_TOKEN
  - secretKey: REDIS_AUTH_TOKEN
    remoteRef:
      key: utterai-dev-tokyo/redis-auth-token
      property: REDIS_AUTH_TOKEN
