---
apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-api-config
data:
  APP_ENV: dev
  LOG_LEVEL: DEBUG
  FRONTEND_ORIGIN: https://d129p1nkqgquw3.cloudfront.net
  CORS_ALLOW_ORIGINS: https://d129p1nkqgquw3.cloudfront.net
  DB_HOST: utterai-dev-rds.c76womumyurf.ap-northeast-2.rds.amazonaws.com
  REDIS_HOST: master.utterai-dev-redis.kk4y3f.apn2.cache.amazonaws.com
  S3_BUCKET_AUDIO: utterai-dev-raw-audio
  S3_BUCKET_TEMPLATE: utterai-dev-documents
  S3_BUCKET_TRANSCRIPT: utterai-dev-transcripts
  SQS_AUDIO_PREPROCESS_QUEUE_URL: https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-dev-audio-preprocess-queue
  SQS_REPORT_ANALYSIS_QUEUE_URL: https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-dev-report-analysis-queue
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev,team=utterai
  CLOUDWATCH_LOG_GROUP: "/aws/eks/utterai-dev/backend"
  CORS_ORIGINS: '["https://d129p1nkqgquw3.cloudfront.net","http://localhost:5173"]'
