apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: utterai-ai-service-pdb
  namespace: utterai-ai-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: utterai-ai-service