---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- "../../base"
- hpa-cpu-worker.yaml
- hpa-ml-gpu-worker.yaml
- hpa-batch-worker.yaml
images:
- name: utterai-ai-cpu
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-ai-cpu'
  newTag: dev-e62f7f6
- name: utterai-ai-gpu
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-ai-gpu'
  newTag: dev-e62f7f6
