---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-cpu-worker
  namespace: utterai-ai-cpu
spec:
  template:
    spec:
      containers:
        - name: worker
          env:
            - name: APP_ENV
              value: dev
            - name: AWS_REGION
              value: ap-northeast-1
            - name: SQS_AUDIO_PREPROCESS_QUEUE_URL
              value: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-audio-preprocess-queue
            - name: SQS_GPU_INFERENCE_QUEUE_URL
              value: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-gpu-inference-queue
            - name: SQS_REPORT_ANALYSIS_QUEUE_URL
              value: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-report-analysis-queue
            - name: S3_BUCKET_REPORT
              value: utterai-dev-tokyo-reports
            - name: S3_BUCKET_AUDIO
              value: utterai-dev-tokyo-raw-audio
            - name: LOG_LEVEL
              value: DEBUG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-ml-gpu-worker
  namespace: utterai-ai-gpu
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: ml-gpu-worker
          env:
            - name: APP_ENV
              value: dev
            - name: AWS_REGION
              value: ap-northeast-1
            - name: SQS_GPU_INFERENCE_QUEUE_URL
              value: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-gpu-inference-queue
            - name: SQS_REPORT_ANALYSIS_QUEUE_URL
              value: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-report-analysis-queue
            - name: S3_BUCKET_AUDIO
              value: utterai-dev-tokyo-raw-audio
            - name: S3_BUCKET_REPORT
              value: utterai-dev-tokyo-reports
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-batch-worker
  namespace: utterai-batch
spec:
  template:
    spec:
      containers:
        - name: worker
          env:
            - name: APP_ENV
              value: dev
            - name: AWS_REGION
              value: ap-northeast-1
            - name: SQS_RAG_INGEST_QUEUE_URL
              value: https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-rag-ingest-queue
            - name: S3_BUCKET_RAG
              value: utterai-dev-tokyo-rag-ingest
