apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-ai-worker-config
data:
  APP_ENV: "dev"
  LOG_LEVEL: "DEBUG"
  AWS_REGION: "ap-northeast-1"
  S3_BUCKET_AUDIO: "utterai-dev-tokyo-raw-audio"
  S3_BUCKET_REPORT: "utterai-dev-tokyo-reports"
  S3_BUCKET_RAG: "utterai-dev-tokyo-rag-ingest"
  S3_BUCKET_TEMPLATE: "utterai-dev-tokyo-template"
  S3_BUCKET_TRANSCRIPT: "utterai-dev-tokyo-transcripts"
  SQS_AUDIO_PREPROCESS_QUEUE_URL: "https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-audio-preprocess-queue"
  SQS_GPU_INFERENCE_QUEUE_URL: "https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-gpu-inference-queue"
  SQS_REPORT_ANALYSIS_QUEUE_URL: "https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-report-analysis-queue"
  SQS_RAG_INGEST_QUEUE_URL: "https://sqs.ap-northeast-1.amazonaws.com/032886669461/utterai-dev-tokyo-rag-ingest-queue"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev,team=utterai"
