---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-worker-external-secret
  namespace: utterai-ai-gpu
spec:
  data:
    - secretKey: DB_USER
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "arn:aws:secretsmanager:ap-northeast-2:032886669461:secret:rds!db-ed45d939-3e0a-4a5f-a3c3-715acd1ad31f-0Xad4o"
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_NAME
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cpu-worker-external-secret
  namespace: utterai-ai-cpu
spec:
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: utterai-dev/cpu-worker-secret
        property: HF_TOKEN
    - secretKey: DB_USER
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "arn:aws:secretsmanager:ap-northeast-2:032886669461:secret:rds!db-ed45d939-3e0a-4a5f-a3c3-715acd1ad31f-0Xad4o"
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_NAME
    - secretKey: BE_DB_USER
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_USER
    - secretKey: BE_DB_PASSWORD
      remoteRef:
        key: "arn:aws:secretsmanager:ap-northeast-2:032886669461:secret:rds!db-ed45d939-3e0a-4a5f-a3c3-715acd1ad31f-0Xad4o"
        property: password
    - secretKey: BE_DB_HOST
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_HOST
    - secretKey: BE_DB_PORT
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_PORT
    - secretKey: BE_DB_NAME
      remoteRef:
        key: utterai-dev/ai-worker-secret
        property: DB_NAME
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gpu-worker-external-secret
  namespace: utterai-ai-gpu
spec:
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: utterai-dev/gpu-worker-secret
        property: HF_TOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-ingest-external-secret
  namespace: utterai-batch
spec:
  data:
    - secretKey: DB_USER
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "arn:aws:secretsmanager:ap-northeast-2:032886669461:secret:rds!db-ed45d939-3e0a-4a5f-a3c3-715acd1ad31f-0Xad4o"
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_NAME
