apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gpu-worker-external-secret
  namespace: utterai-ai-gpu
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: gpu-worker-secret
    creationPolicy: Owner
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: utterai-dev/gpu-worker-secret
        property: HF_TOKEN
