---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-service-external-secret
spec:
  data:
    - secretKey: HF_TOKEN
      remoteRef:
        key: utterai-dev-tokyo/cpu-worker-secret
        property: HF_TOKEN
    - secretKey: DB_USER
      remoteRef:
        key: utterai-dev-tokyo/rag-ingest-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: utterai-dev-tokyo/rag-ingest-secret
        property: DB_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: utterai-dev-tokyo/rag-ingest-secret
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: utterai-dev-tokyo/rag-ingest-secret
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: utterai-dev-tokyo/rag-ingest-secret
        property: DB_NAME
