apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-ai-service-config
data:
  APP_ENV: "dev"
  LOG_LEVEL: "DEBUG"
  S3_BUCKET_AUDIO: "utterai-dev-raw-audio"
  S3_BUCKET_RAG: "utterai-dev-rag-ingest"
  SQS_AUDIO_PREPROCESS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-dev-audio-preprocess-queue"
  SQS_RAG_INGEST_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-dev-rag-ingest-queue"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev,team=utterai,service=ai-service"