apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../external-secrets/base
  - ../observability/overlays/dev-tokyo
  - ../image-pruner/base
  - ../karpenter/overlays/dev

patches:
  - path: patch-cluster-secret-store.yaml
