apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-ai-api-sa
  annotations:
    # TODO: 실제 prod AI API IRSA role ARN으로 교체합니다.
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/utterai-prod-ai-api-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-ai-cpu-worker-sa
  annotations:
    # TODO: 실제 prod AI CPU worker IRSA role ARN으로 교체합니다.
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/utterai-prod-ai-cpu-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-ai-ml-gpu-worker-sa
  annotations:
    # TODO: 실제 prod AI ML GPU worker IRSA role ARN으로 교체합니다.
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/utterai-prod-ai-ml-gpu-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-ai-llm-gpu-worker-sa
  annotations:
    # TODO: 실제 prod AI LLM GPU worker IRSA role ARN으로 교체합니다.
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/utterai-prod-ai-llm-gpu-irsa-role
