apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-ai-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-ai-cpu-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-ai-ml-gpu-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utterai-ai-llm-gpu-worker
spec:
  replicas: 1
