apiVersion: v1
kind: Namespace
metadata:
  name: utterai-prod-ai-worker
  labels:
    app.kubernetes.io/part-of: utterai
    utterai.io/environment: prod
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
