apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-ai-worker-config
data:
  APP_ENV: "prod"
  LOG_LEVEL: "INFO"
  AWS_REGION: "ap-northeast-2"
  BEDROCK_REGION: "ap-northeast-2"
  BEDROCK_REPORT_MODEL_ID: "global.anthropic.claude-haiku-4-5-20251001-v1:0"
  S3_BUCKET_AUDIO: "utterai-prod-raw-audio"
  S3_BUCKET_REPORT: "utterai-prod-reports"
  S3_BUCKET_RAG: "utterai-prod-rag-ingest"
  S3_BUCKET_TEMPLATE: "utterai-prod-template"
  S3_BUCKET_TRANSCRIPT: "utterai-prod-transcripts"
  SQS_AUDIO_PREPROCESS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-prod-audio-preprocess-queue"
  SQS_GPU_INFERENCE_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-prod-gpu-inference-queue"
  SQS_REPORT_ANALYSIS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-prod-report-analysis-queue"
  SQS_RAG_INGEST_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-prod-rag-ingest-queue"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.utterai-observability.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod,team=utterai"
