apiVersion: v1
kind: Namespace
metadata:
  name: utterai-api
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utterai-ai-cpu
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utterai-ai-gpu
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utterai-batch
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utterai-ai-api
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utterai-observability
  labels:
    app.kubernetes.io/part-of: utterai
