apiVersion: v1
kind: Namespace
metadata:
  name: utter-api
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utter-ai-cpu
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utter-ai-gpu
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utter-batch
  labels:
    app.kubernetes.io/part-of: utterai
---
apiVersion: v1
kind: Namespace
metadata:
  name: utter-observability
  labels:
    app.kubernetes.io/part-of: utterai
