---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utterai-dev-ai-worker
resources:
- namespace.yaml
- "../../base"
images:
- name: utterai-ai-cpu
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-ai-cpu'
  newTag: dev-e24a4bd
- name: utterai-ai-gpu
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-ai-gpu'
  newTag: dev-e24a4bd
patches:
- path: patch-configmap.yaml
- path: patch-serviceaccount.yaml
