---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- "../../base"
images:
- name: utterai-ai-cpu
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-ai-cpu'
  newTag: dev-63dd74c
- name: utterai-ai-gpu
  newName: '032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-ai-gpu'
  newTag: dev-5355c31
