---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-api-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: backend-api-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: arn:aws:secretsmanager:ap-northeast-2:032886669461:secret:rds!db-ed45d939-3e0a-4a5f-a3c3-715acd1ad31f-0Xad4o
      property: password
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: utterai-dev/backend-api-secret
      property: JWT_SECRET_KEY
  - secretKey: INTERNAL_CALLBACK_TOKEN
    remoteRef:
      key: utterai-dev/backend-api-secret
      property: INTERNAL_CALLBACK_TOKEN
  - secretKey: REDIS_AUTH_TOKEN
    remoteRef:
      key: utterai-dev/redis-auth-token
      property: REDIS_AUTH_TOKEN
