apiVersion: v1
kind: Service
metadata:
  name: utterai-backend-service
  labels:
    app.kubernetes.io/name: utterai-backend
    app.kubernetes.io/part-of: utterai
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: utterai-backend
  ports:
    - name: http
      port: 80
      targetPort: http
