apiVersion: v1
kind: ServiceAccount
metadata:
  name: utterai-api-sa
  annotations:
    # TODO: prod backend IRSA role ARN으로 교체합니다.
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/utterai-prod-backend-irsa-role
