apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utterai-api

resources:
  - namespace.yaml
  - ../../base

# TODO: GitHub Actions CD에서 newName/newTag를 실제 ECR image로 갱신합니다.
images:
  - name: utterai-backend-blue
    newName: 032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-backend
    newTag: dev-9be32c7
  - name: utterai-backend-green
    newName: 032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-backend
    newTag: dev-9be32c7

patches:
  - path: patch-active-service.yaml
  - path: patch-configmap.yaml
  - path: patch-serviceaccount.yaml
