apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utterai-api

resources:
  - namespace.yaml
  - ../../base

# TODO: GitHub Actions CD에서 newName/newTag를 실제 ECR image로 갱신합니다.
images:
  - name: utterai-backend
    newName: 032886669461.dkr.ecr.ap-northeast-2.amazonaws.com/utterai-backend
    newTag: dev-63dd74c

patches:
  - path: patch-configmap.yaml
  - path: patch-serviceaccount.yaml
