apiVersion: v1
kind: ConfigMap
metadata:
  name: utterai-api-config
data:
  APP_ENV: "dev"
  LOG_LEVEL: "DEBUG"
  FRONTEND_ORIGIN: "https://d4kxfdssuth29.cloudfront.net"
  CORS_ALLOW_ORIGINS: "https://d4kxfdssuth29.cloudfront.net"
  RAW_AUDIO_BUCKET: "utterai-dev-raw-audio"
  SQS_AUDIO_PREPROCESS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/032886669461/utterai-dev-audio-preprocess-queue"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.utterai-observability.svc.cluster.local:4318"
  CLOUDWATCH_LOG_GROUP: "/aws/eks/utterai-dev/backend"
