---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-ingest-external-secret
  namespace: utterai-batch
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rag-ingest-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-2:032886669461:secret:rds!db-ed45d939-3e0a-4a5f-a3c3-715acd1ad31f-0Xad4o
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_PORT
    - secretKey: DB_NAME
      remoteRef:
        key: utterai-dev/rag-ingest-secret
        property: DB_NAME