---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: utterai-api-role
  namespace: utterai-api
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: utterai-api-rolebinding
  namespace: utterai-api
subjects:
  - kind: ServiceAccount
    name: utterai-api-sa
    namespace: utterai-api
roleRef:
  kind: Role
  name: utterai-api-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: utterai-cpu-worker-role
  namespace: utterai-ai-cpu
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: utterai-cpu-worker-rolebinding
  namespace: utterai-ai-cpu
subjects:
  - kind: ServiceAccount
    name: utterai-cpu-worker-sa
    namespace: utterai-ai-cpu
roleRef:
  kind: Role
  name: utterai-cpu-worker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: utterai-gpu-worker-role
  namespace: utterai-ai-gpu
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: utterai-ml-gpu-worker-rolebinding
  namespace: utterai-ai-gpu
subjects:
  - kind: ServiceAccount
    name: utterai-ml-gpu-worker-sa
    namespace: utterai-ai-gpu
roleRef:
  kind: Role
  name: utterai-gpu-worker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: utterai-llm-gpu-worker-rolebinding
  namespace: utterai-ai-gpu
subjects:
  - kind: ServiceAccount
    name: utterai-llm-gpu-worker-sa
    namespace: utterai-ai-gpu
roleRef:
  kind: Role
  name: utterai-gpu-worker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: utterai-batch-worker-role
  namespace: utterai-batch
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: utterai-batch-worker-rolebinding
  namespace: utterai-batch
subjects:
  - kind: ServiceAccount
    name: utterai-batch-worker-sa
    namespace: utterai-batch
roleRef:
  kind: Role
  name: utterai-batch-worker-role
  apiGroup: rbac.authorization.k8s.io
