apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-ec2nodeclass-default-prod.yaml
    target:
      kind: EC2NodeClass
      name: default
